#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if [ -f frontend/package.json ]; then
	npm --prefix frontend exec commitlint -- --config frontend/.commitlintrc.json --edit "$1"
else
	npx commitlint --edit "$1"
fi
